# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a22be61c8e3e494eac8a1b9f4601855b657c8eab47e141d40658864037969bbf21b1787417e71fc7b3e05bc4c9b744314f44aa4d3eb6039fad19b6440a6945f

test:
  secret_key_base: 1cc7cb13b64bd12efec5bb4c246593d31e8764fbf517c4cdde0a5573fa778f0778f5343bfb1de66deaf08b6bf67324c88daebddf3f641514f9c5f4757d94fb34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
